/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {
  interface AppHome {
    'history': RouterHistory;
  }
  interface AppRace {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppResults {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppRoot {}
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRaceElement extends Components.AppRace, HTMLStencilElement {}
  var HTMLAppRaceElement: {
    prototype: HTMLAppRaceElement;
    new (): HTMLAppRaceElement;
  };

  interface HTMLAppResultsElement extends Components.AppResults, HTMLStencilElement {}
  var HTMLAppResultsElement: {
    prototype: HTMLAppResultsElement;
    new (): HTMLAppResultsElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-race': HTMLAppRaceElement;
    'app-results': HTMLAppResultsElement;
    'app-root': HTMLAppRootElement;
  }
}

declare namespace LocalJSX {
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {
    'history'?: RouterHistory;
  }
  interface AppRace extends JSXBase.HTMLAttributes<HTMLAppRaceElement> {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }
  interface AppResults extends JSXBase.HTMLAttributes<HTMLAppResultsElement> {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-race': AppRace;
    'app-results': AppResults;
    'app-root': AppRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


